
if GetLocale() ~= "zhCN" then	-- chinese simplified
	return
end





---------------
-- Installer --
---------------
	SYNCUI_STRING_INSTALL_BTN_FINISH = "完成"
	SYNCUI_STRING_INSTALL_BTN_INSTALL = "安装"
	SYNCUI_STRING_INSTALL_COMPLETE = "点击 '完成' 按钮关闭安装向导."
	SYNCUI_STRING_INSTALL_CONTINUE = "点击 '安装' 按钮继续安装."
	SYNCUI_STRING_INSTALL_IN_PROGRESS = "安装正在进行中."
	SYNCUI_STRING_INSTALL_WELCOME = "欢迎使用 "..SYNCUI_STRING_UI_LABEL
-------------
-- Options --
-------------
	SYNCUI_STRING_APPEARANCE_COLOR_MODE = "颜色样式"
	SYNCUI_STRING_APPEARANCE_RAINBOW = "彩虹"
	SYNCUI_STRING_APPEARANCE_PULSE = "呼吸效果"
	SYNCUI_STRING_APPEARANCE_SOLID = "静态描边"
	SYNCUI_STRING_APPEARANCE_FONTS = "字体"
	SYNCUI_STRING_AURAS = "光环"
	SYNCUI_STRING_AURAS_COLORIZE_TIMER = "数字染色"
	SYNCUI_STRING_AURAS_DISABLE_SPIRAL = "停用旋转阴影"
	SYNCUI_STRING_AURAS_FILTER_DEBUFFS = "只显示我的减益效果"
	SYNCUI_STRING_AURAS_NUMERIC_TIMERS = "启用数字计时"
	SYNCUI_STRING_AURAS_REACTIVE_AURAS = "法术监视"
	SYNCUI_STRING_AURAS_ENTER_SPELL_ID = "输入法术ID"
	SYNCUI_STRING_UNITFRAMES = "单位框架"
	SYNCUI_STRING_UNITFRAMES_DISABLE_DEFAULT = "你要关闭暴雪自带的小队框架么?"
	SYNCUI_STRING_UNITFRAMES_ENABLE_DEFAULT = "你要关闭暴雪自带的团队框架么?"
	SYNCUI_STRING_UNITFRAMES_SORTBY = "整理队伍规则:"
	SYNCUI_STRING_UNITFRAMES_USEDEFAULT = "使用系统自带团队框架"
	SYNCUI_STRING_QUESTS_AUTO_ACCEPT = "自动接受任务"
	SYNCUI_STRING_QUESTS_AUTO_SHARE = "自动分享已有任务"
	SYNCUI_STRING_QUESTS_AUTO_TURN_IN = "自动完成已做好的任务"
	SYNCUI_STRING_QUESTS_INCLUDE_DAILY = "包括日常/周常任务"
	SYNCUI_STRING_QUESTS_DISABLE_TRACKER = "隐藏暴雪自带的任务追踪"
	SYNCUI_STRING_QUESTS_IGNORE = "Will be ignored while holding |cFF66FF00Shift|r"
	SYNCUI_STRING_MISC = "其他"
	SYNCUI_STRING_MISC_AUTO_REPAIR = "自动修理装备"
	SYNCUI_STRING_MISC_AUTO_SELL = "自动出售无用的物品"
	SYNCUI_STRING_MISC_AUTO_WORK_ORDER = "自动开始订单"
	SYNCUI_STRING_MISC_DISABLE_AFK = "禁用 暂离/飞行 动画"
	SYNCUI_STRING_MISC_GUILD_REPAIR = "优先使用公会修理"
	SYNCUI_STRING_MISC_SKIP_CINEMATIC = "跳过动画"
	SYNCUI_STRING_PROFILES = "配置"
	SYNCUI_STRING_PROFILES_CREATE = "创建新配置文件:"
	SYNCUI_STRING_PROFILES_SELECT = "选择配置文件:"
	SYNCUI_STRING_PROFILES_DELETE = "删除个人资料:"
	SYNCUI_STRING_PROFILES_DELETE_QUERY = "是否要删除所选的配置文件: |cFF66FF00%s|r"
	SYNCUI_STRING_PROFILES_COPY = "从配置文件复制:"
	SYNCUI_STRING_PROFILES_COPY_QUERY = "你想覆盖当前的个人资料: |cFF66FF00%s|r?"
	SYNCUI_STRING_BROKER = "组件栏"
	SYNCUI_STRING_PLACEMENT_TOOL = "框体解锁"
	SYNCUI_STRING_PLACEMENT_TOOL_CLICK_TO_RESET = "|cFF66FF00Shift+鼠标右击|r 来重置定位"
	SYNCUI_STRING_PLACEMENT_TOOL_RESET_POSITION = "你确定要重置所有框体么?"
	SYNCUI_STRING_PLACEMENT_TOOL_SELECT = "选择专精:"
	SYNCUI_STRING_PLACEMENT_TOOL_COPY = "Copy from spec:"
	SYNCUI_STRING_PLACEMENT_TOOL_COPY_QUERY = "Do you want to overwrite:\n\n |T%s:14:14:0:0:64:64:5:59:5:59|t |cFF66FF00%s|r?"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_ALERTS = "通知"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_BUFFS = "玩家增益效果"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_CASTBAR = "施法条"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_ZONE_ABILITY = "区域技能"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_ENVIRONMENT_BAR = "环境条"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_TOOLTIP = "鼠标提示"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_VEHICLE = "载具"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_WORLD_MARK_BAR = "世界标记（光柱）"
--------------
-- Bindings --
--------------
	SYNCUI_STRING_BINDING_USE_ACTIVE_QUEST_ITEM = "使用目前任务物品"
	SYNCUI_STRING_BINDING_TOGGLE_SIDEBAR = "切换侧边栏"
-------------------
-- Group Control --
-------------------
	SYNCUI_STRING_GROUP_CONTROL_LAYOUT = "布局: "
	SYNCUI_STRING_GROUP_CONTROL_LAYOUT_HEAL = "治疗"
	SYNCUI_STRING_GROUP_CONTROL_LAYOUT_NORMAL = "标准"
	SYNCUI_STRING_GROUP_CONTROL_MAXIMIZE_RAID = "显示团队框架"
	SYNCUI_STRING_GROUP_CONTROL_MINIMIZE_RAID = "隐藏团队框架"
	SYNCUI_STRING_LOOTMETHOD_CURRENT_SPEC = "专精"
---------------
-- Raid Tool --
---------------
	SYNCUI_STRING_RAID_TOOL = "团队工具"
	SYNCUI_STRING_RAID_TOOL_COMPILATION = "团队工具设置"
	SYNCUI_STRING_RAID_TOOL_LOCKOUTS = "团队工具关闭"
	SYNCUI_STRING_RAID_TOOL_WORLD_MARKS = "世界标记（光柱）"
	SYNCUI_STRING_RAID_TOOL_CLEAR_WORLD_MARKS = "|cFF66FF00Shift-点击|r 删除"
------------
-- Bag UI --
------------
	SYNCUI_STRING_BAGS_MANAGE_CONTAINERS = "分类设置"
	SYNCUI_STRING_BAGS_DROP_SLOT = "可用空格"
	SYNCUI_STRING_BAGS_RESTACK = "重新叠放"
-------------
-- Minimap --
-------------
	SYNCUI_STRING_CLOCK_TOGGLE_DISPLAY = "|cFF66FF00Shift+左击|r 切换本地/服务器计时"
	SYNCUI_STRING_CLOCK_TOGGLE_HOUR_MODE = "|cFF66FF00左击|r 切换24小时时间制"
	SYNCUI_STRING_CLOCK_TOGGLE_STOPWATCH = "|cFF66FF00右击|r 打开计时器"
--------------
-- TalentUI --
--------------
	SYNCUI_STRING_TALENT_AVAILABE = "<%d级才可选择使用>"
	SYNCUI_STRING_TALENT_SHOW_ABILITIES = "<按住Shift键查看该专精基础技能>"
-----------------------
-- OBJECTIVE TRACKER --
-----------------------
	SYNCUI_STRING_OBJ_TRACKER = "任务追踪器"
	SYNCUI_STRING_OBJ_TRACKER_FILTER_QUESTS = "过滤任务"
	SYNCUI_STRING_OBJ_TRACKER_FILTER_ACHIEVEMENTS = "过滤成就"
	SYNCUI_STRING_OBJ_TRACKER_MINIMIZE = "最小化追踪器"
----------
-- MISC --
----------
	SYNCUI_STRING_STORE = "商城"
	SYNCUI_STRING_CHANGE_LOG = "更新日志"
	SYNCUI_STRING_ENTER_NAME = "输入名称"
	SYNCUI_STRING_SKIP_TURN = "跳过本回合"	
	SYNCUI_STRING_SPELLID = "|cFF66FF00法术ID: |r %d"
	SYNCUI_STRING_AURAID = "|cFF66FF00光环ID:|r %d"
	SYNCUI_STRING_ITEMID = "|cFF66FF00物品ID:|r %d"
	SYNCUI_STRING_MEMORY = "内存"
	SYNCUI_STRING_MEMORY_LABEL = "插件占用"
	SYNCUI_STRING_EXP = "经验"
	SYNCUI_STRING_LATENCY = "延迟"
	SYNCUI_STRING_NOT_ONLINE = "没有好友在线!"
	SYNCUI_STRING_REALM = "范围"
	SYNCUI_STRING_ALL_REALMS = "全部区域"
	SYNCUI_STRING_SESSION = "收益:"
	SYNCUI_STRING_SWITCH_DISPLAY = "|cFF66FF00点击|r切换显示"
	SYNCUI_STRING_PRESS_TO_CANCEL = "按|cFF66FF00%s|r 取消"
	SYNCUI_STRING_BROKEN = "|cFFFF0000损坏|r"