
if GetLocale() ~= "zhTW" then	-- traditional Chinese
	return
end





---------------
-- Installer --
---------------
	SYNCUI_STRING_INSTALL_BTN_FINISH = "完成"
	SYNCUI_STRING_INSTALL_BTN_INSTALL = "安裝"
	SYNCUI_STRING_INSTALL_COMPLETE = "請按 '完成' 結束安裝"
	SYNCUI_STRING_INSTALL_CONTINUE = "請按 '安裝' 繼續下一步"
	SYNCUI_STRING_INSTALL_IN_PROGRESS = "正在進行安裝"
	SYNCUI_STRING_INSTALL_WELCOME = "歡迎使用 "..SYNCUI_STRING_UI_LABEL
-------------
-- Options --
-------------
	SYNCUI_STRING_APPEARANCE_COLOR_MODE = "色彩模式"
	SYNCUI_STRING_APPEARANCE_RAINBOW = "彩虹"
	SYNCUI_STRING_APPEARANCE_PULSE = "變幻"
	SYNCUI_STRING_APPEARANCE_SOLID = "固定"
	SYNCUI_STRING_APPEARANCE_FONTS = "字體"
	SYNCUI_STRING_AURAS = "光環"
	SYNCUI_STRING_AURAS_COLORIZE_TIMER = "彩色計時數字"
	SYNCUI_STRING_AURAS_DISABLE_SPIRAL = "停用旋轉陰影"
	SYNCUI_STRING_AURAS_FILTER_DEBUFFS = "只顯示我施放的減益效果"
	SYNCUI_STRING_AURAS_NUMERIC_TIMERS = "顯示計時數字"
	SYNCUI_STRING_AURAS_REACTIVE_AURAS = "監控光環"
	SYNCUI_STRING_AURAS_ENTER_SPELL_ID = "輸入法術ID"
	SYNCUI_STRING_UNITFRAMES = "單位框架"
	SYNCUI_STRING_UNITFRAMES_DISABLE_DEFAULT = "是否要停用遊戲內建的團隊框架?"
	SYNCUI_STRING_UNITFRAMES_ENABLE_DEFAULT = "是否要使用遊戲內建的團隊框架?"
	SYNCUI_STRING_UNITFRAMES_SORTBY = "團隊框架排序方式:"
	SYNCUI_STRING_UNITFRAMES_USEDEFAULT = "使用預設的團隊框架"
	SYNCUI_STRING_QUESTS_AUTO_ACCEPT = "自動接受任務"
	SYNCUI_STRING_QUESTS_AUTO_SHARE = "自動分享已接的任務"
	SYNCUI_STRING_QUESTS_AUTO_TURN_IN = "自動交回已完成的任務"
	SYNCUI_STRING_QUESTS_INCLUDE_DAILY = "包括每日和每週任務"
	SYNCUI_STRING_QUESTS_DISABLE_TRACKER = "停用預設的任務目標清單"
	SYNCUI_STRING_QUESTS_IGNORE = "Will be ignored while holding |cFF66FF00Shift|r"
	SYNCUI_STRING_MISC = "其他"
	SYNCUI_STRING_MISC_AUTO_REPAIR = "自動修理裝備"
	SYNCUI_STRING_MISC_AUTO_SELL = "自動賣垃圾"
	SYNCUI_STRING_MISC_AUTO_WORK_ORDER = "啟用自動下訂單"
	SYNCUI_STRING_MISC_DISABLE_AFK = "停用 AFK/飛行模式"
	SYNCUI_STRING_MISC_GUILD_REPAIR = "優先使用公會修裝"
	SYNCUI_STRING_MISC_SKIP_CINEMATIC = "跳過動畫"
	SYNCUI_STRING_PROFILES = "Profiles"
	SYNCUI_STRING_PROFILES_CREATE = "Create new profile:"
	SYNCUI_STRING_PROFILES_SELECT = "Select profile:"
	SYNCUI_STRING_PROFILES_DELETE = "Delete profile:"
	SYNCUI_STRING_PROFILES_DELETE_QUERY = "Do you want to delete the selected profile: |cFF66FF00%s|r"
	SYNCUI_STRING_PROFILES_COPY = "Copy from profile:"
	SYNCUI_STRING_PROFILES_COPY_QUERY = "Do you want to overwrite your current profile: |cFF66FF00%s|r?"
	SYNCUI_STRING_BROKER = "資訊列"
	SYNCUI_STRING_PLACEMENT_TOOL = "版面配置工具"
	SYNCUI_STRING_PLACEMENT_TOOL_CLICK_TO_RESET = "|cFF66FF00Shift+右鍵|r 重設位置"
	SYNCUI_STRING_PLACEMENT_TOOL_RESET_POSITION = "是否要重設所有框架的位置?"
	SYNCUI_STRING_PLACEMENT_TOOL_SELECT_SPEC = "選擇專精:"
	SYNCUI_STRING_PLACEMENT_TOOL_COPY = "Copy from spec:"
	SYNCUI_STRING_PLACEMENT_TOOL_COPY_QUERY = "Do you want to overwrite:\n\n |T%s:14:14:0:0:64:64:5:59:5:59|t |cFF66FF00%s|r?"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_ALERTS = "通知"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_BUFFS = "玩家\n增益效果"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_CASTBAR = "施法條"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_ZONE_ABILITY = "區域特殊技能"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_ENVIRONMENT_BAR = "環境計時條"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_TOOLTIP = "滑鼠提示"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_VEHICLE = "載具"
	SYNCUI_STRING_PLACEMENT_TOOL_LABEL_WORLD_MARK_BAR = "世界標記圖示列"
--------------
-- Bindings --
--------------
	SYNCUI_STRING_BINDING_USE_ACTIVE_QUEST_ITEM = "使用目前任務物品"
	SYNCUI_STRING_BINDING_TOGGLE_SIDEBAR = "Toggle Sidebar"
-------------------
-- Group Control --
-------------------
	SYNCUI_STRING_GROUP_CONTROL_LAYOUT = "選擇版面配置:"
	SYNCUI_STRING_GROUP_CONTROL_LAYOUT_HEAL = "治療者"
	SYNCUI_STRING_GROUP_CONTROL_LAYOUT_NORMAL = "一般"
	SYNCUI_STRING_GROUP_CONTROL_MAXIMIZE_RAID = "顯示團隊框架"
	SYNCUI_STRING_GROUP_CONTROL_MINIMIZE_RAID = "隱藏團隊框架"
	SYNCUI_STRING_LOOTMETHOD_CURRENT_SPEC = "目前專精"
---------------
-- Raid Tool --
---------------
	SYNCUI_STRING_RAID_TOOL = "團隊工具"
	SYNCUI_STRING_RAID_TOOL_COMPILATION = "團隊編組"
	SYNCUI_STRING_RAID_TOOL_LOCKOUTS = "團隊進度"
	SYNCUI_STRING_RAID_TOOL_WORLD_MARKS = "世界標記"
	SYNCUI_STRING_RAID_TOOL_CLEAR_WORLD_MARKS = "|cFF66FF00Shift-左鍵|r 清除世界標記"
------------
-- Bag UI --
------------
	SYNCUI_STRING_BAGS_MANAGE_CONTAINERS = "管理分類"
	SYNCUI_STRING_BAGS_DROP_SLOT = "空欄位"
	SYNCUI_STRING_BAGS_RESTACK = "重新疊放"
-------------
-- Minimap --
-------------
	SYNCUI_STRING_CLOCK_TOGGLE_DISPLAY = "|cFF66FF00Shift-左鍵|r 切換顯示 服務器/當地 時間"
	SYNCUI_STRING_CLOCK_TOGGLE_HOUR_MODE = "|cFF66FF00左鍵|r 切換24小時模式"
	SYNCUI_STRING_CLOCK_TOGGLE_STOPWATCH = "|cFF66FF00Right-右鍵|r 顯示/隱藏碼表"
--------------
-- TalentUI --
--------------
	SYNCUI_STRING_TALENT_AVAILABE = "<此功能將在%d級開放>"
	SYNCUI_STRING_TALENT_SHOW_ABILITIES = "<按住 Shift 鍵顯示屬性>"
-----------------------
-- OBJECTIVE TRACKER --
-----------------------
	SYNCUI_STRING_OBJ_TRACKER = "Objective Tracker"
	SYNCUI_STRING_OBJ_TRACKER_FILTER_QUESTS = "Filter Quests"
	SYNCUI_STRING_OBJ_TRACKER_FILTER_ACHIEVEMENTS = "Filter Achievements"
	SYNCUI_STRING_OBJ_TRACKER_MINIMIZE = "Minimize Tracker"
----------
-- MISC --
----------
	SYNCUI_STRING_STORE = "遊戲商城"
	SYNCUI_STRING_CHANGE_LOG = "更新資訊"
	SYNCUI_STRING_ENTER_NAME = "輸入名稱"
	SYNCUI_STRING_SKIP_TURN = "跳過這個回合"
	SYNCUI_STRING_SPELLID = "|cFF66FF00法術ID:|r %d"
	SYNCUI_STRING_AURAID = "|cFF66FF00光環ID:|r %d"
	SYNCUI_STRING_ITEMID = "|cFF66FF00項目ID:|r %d"
	SYNCUI_STRING_MEMORY = "記憶體"
	SYNCUI_STRING_MEMORY_LABEL = "插件記憶體"
	SYNCUI_STRING_EXP = "經驗值"
	SYNCUI_STRING_LATENCY = "網路延遲"
	SYNCUI_STRING_NOT_ONLINE = "沒有好友在線上!"
	SYNCUI_STRING_REALM = "伺服器"
	SYNCUI_STRING_ALL_REALMS = "所有伺服器"
	SYNCUI_STRING_SESSION = "本次登入:"
	SYNCUI_STRING_SWITCH_DISPLAY = "|cFF66FF00點一下|r 切換顯示"
	SYNCUI_STRING_PRESS_TO_CANCEL = "按下|cFF66FF00%s|r 取消"
	SYNCUI_STRING_BROKEN = "|cFFFF0000破碎|r"